CREATE TABLE IF NOT EXISTS PRODUCT (
    ID BIGSERIAL PRIMARY KEY,
    SKU VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS PRODUCT_ATTRIBUTE (
    ID BIGSERIAL PRIMARY KEY,
    PRODUCT_ID BIGINT NOT NULL,
    PRICE DECIMAL(5, 2) NOT NULL,
    STORE BIGINT NOT NULL,
    QUANTITY INT DEFAULT 0,
    AVAILABLE BOOLEAN DEFAULT FALSE,
    FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(ID)
);

CREATE UNIQUE INDEX sku_idx ON PRODUCT (SKU);
CREATE UNIQUE INDEX store_id_and_product_id_idx ON PRODUCT_ATTRIBUTE (STORE, PRODUCT_ID);