CREATE TABLE IF NOT EXISTS PRODUCT (
    ID BIGSERIAL PRIMARY KEY,
    SKU VARCHAR(255) NOT NULL,
);

CREATE TABLE IF NOT EXISTS PRODUCT_ATTRIBUTE (
    ID BIGSERIAL PRIMARY KEY,
    PRODUCT_ID BIGINT NOT NULL,
    PRICE DECIMAL(5, 2) NOT NULL,
    STORE INT NOT NULL,
    QUANTITY INT DEFAULT 0,
    AVAILABLE BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_product_id FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(ID)
);